######################################################################
# Automatically generated by qmake (3.0) ?? ???. 17 02:50:03 2016
######################################################################
QT += widgets

TEMPLATE = app
TARGET = hello
INCLUDEPATH += .

# Input
HEADERS += mDialog.h
SOURCES += main.cpp mDialog.cpp

FORMS +=
