######################################################################
# Automatically generated by qmake (3.0) ?? ???. 17 02:29:37 2016
######################################################################
QT += widgets

TEMPLATE = app
TARGET = hello
INCLUDEPATH += .

# Input
SOURCES += main.cpp
